version: '3'

services:
  dnsproxy:
    image: dnsproxy/AdguardHome:latest
    container_name: dnsproxy
    restart: always
    #volumes:
            #- /etc/letsencrypt:/etc/letsencrypt # Uncomment this line to reuse existing cert and key
    environment:
      LISTEN: "0.0.0.0" 
      SRVPORT: "784"
      DOMAIN: "example.org" # Your domain name required
      EMAIL: "email@example.org"
      UPSTREAM_ADDR: "1.1.1.1:53"
      RATELIMIT: "30"
      EDNS: "ON"
      LOCALPORT: "1111" # Any local port #
      MODE: "server"
      PROTO: "quic"
      DRYRUN: "--dry-run" # Uncomment this option to test letsencrypt cert generation process
    ports:
            - 80:80 # Port 80 is mandatory for letsencrypt to generate cert/keys successfully
            - 443:443
            - 784:784/udp
            - 853:853
            - 1111:1111/udp
